export * from "./patterns"
export * from "./staffValidation"
export * from "./studentValidation"
export * from "./adminValidation"
export * from "./principalValidation"
export * from "./schoolSetupValidation"
