"""create_admin_teacher_and_student_profiles

Revision ID: 1ba7d9e67683
Revises: 1f2a4c502626
Create Date: 2026-08-28 19:58:57.262272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ba7d9e67683'
down_revision: Union[str, Sequence[str], None] = '1f2a4c502626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('permissions_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_admin_profiles_department', 'admin_profiles', ['department'], unique=False)
    op.create_index('idx_admin_profiles_employee_code', 'admin_profiles', ['employee_code'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_admin_profiles_user_id_active', 'admin_profiles', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.String(length=150), nullable=False),
    sa.Column('guardian_relation', sa.String(length=50), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=False),
    sa.Column('guardian_email', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_student_profiles_admission_number', 'student_profiles', ['admission_number'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_student_profiles_dob', 'student_profiles', ['date_of_birth'], unique=False)
    op.create_index('idx_student_profiles_roll_number', 'student_profiles', ['roll_number'], unique=False)
    op.create_index('uq_student_profiles_user_id_active', 'student_profiles', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('teacher_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_teacher_profiles_department', 'teacher_profiles', ['department'], unique=False)
    op.create_index('idx_teacher_profiles_designation', 'teacher_profiles', ['designation'], unique=False)
    op.create_index('idx_teacher_profiles_employee_code', 'teacher_profiles', ['employee_code'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_teacher_profiles_user_id_active', 'teacher_profiles', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_teacher_profiles_user_id_active', table_name='teacher_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_teacher_profiles_employee_code', table_name='teacher_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_teacher_profiles_designation', table_name='teacher_profiles')
    op.drop_index('idx_teacher_profiles_department', table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index('uq_student_profiles_user_id_active', table_name='student_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_student_profiles_roll_number', table_name='student_profiles')
    op.drop_index('idx_student_profiles_dob', table_name='student_profiles')
    op.drop_index('idx_student_profiles_admission_number', table_name='student_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('student_profiles')
    op.drop_index('uq_admin_profiles_user_id_active', table_name='admin_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_admin_profiles_employee_code', table_name='admin_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_admin_profiles_department', table_name='admin_profiles')
    op.drop_table('admin_profiles')
    # ### end Alembic commands ###
