"""add_school_theme_and_emblem_fields

Revision ID: 20244e7515a3
Revises: 60e1a71d60a2
Create Date: 2026-09-01 16:01:52.902696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20244e7515a3'
down_revision: Union[str, Sequence[str], None] = '60e1a71d60a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('primary_color', sa.String(length=20), nullable=True))
    op.add_column('schools', sa.Column('emblem_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'emblem_url')
    op.drop_column('schools', 'primary_color')
    # ### end Alembic commands ###
