"""update admin, teacher, student tables

Revision ID: 259771de0f8a
Revises: c7d8e9f0a1b2
Create Date: 2026-08-29 18:44:55.604769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '259771de0f8a'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_staff_designations_active'), table_name='staff_designations', postgresql_where='(is_active IS TRUE)')
    op.drop_index(op.f('idx_staff_designations_designation'), table_name='staff_designations')
    op.drop_index(op.f('idx_staff_designations_scope'), table_name='staff_designations')
    op.drop_index(op.f('idx_staff_designations_user_designation'), table_name='staff_designations')
    op.drop_index(op.f('idx_staff_designations_user_id'), table_name='staff_designations')
    op.drop_table('staff_designations')
    op.drop_index(op.f('idx_admin_profiles_employee_code'), table_name='admin_profiles')
    op.drop_index(op.f('idx_student_profiles_admission_number'), table_name='student_profiles')
    op.drop_index(op.f('idx_student_profiles_roll_number'), table_name='student_profiles')
    op.drop_column('student_profiles', 'roll_number')
    op.drop_index(op.f('idx_teacher_profiles_employee_code'), table_name='teacher_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_teacher_profiles_employee_code'), 'teacher_profiles', ['employee_code'], unique=False)
    op.add_column('student_profiles', sa.Column('roll_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_student_profiles_roll_number'), 'student_profiles', ['roll_number'], unique=False)
    op.create_index(op.f('idx_student_profiles_admission_number'), 'student_profiles', ['admission_number'], unique=False)
    op.create_index(op.f('idx_admin_profiles_employee_code'), 'admin_profiles', ['employee_code'], unique=False)
    op.create_table('staff_designations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.SMALLINT(), autoincrement=False, nullable=False, comment='The type of designation (class teacher, coordinator, etc.)'),
    sa.Column('scope_type', sa.SMALLINT(), autoincrement=False, nullable=False, comment='The scope boundary (school, department, class, section)'),
    sa.Column('scope_id', sa.UUID(), autoincrement=False, nullable=True, comment='ID of the scoped entity. NULL for school-wide scope.'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.UUID(), autoincrement=False, nullable=True, comment='The user who assigned this designation'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('staff_designations_assigned_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('staff_designations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_designations_pkey'))
    )
    op.create_index(op.f('idx_staff_designations_user_id'), 'staff_designations', ['user_id'], unique=False)
    op.create_index(op.f('idx_staff_designations_user_designation'), 'staff_designations', ['user_id', 'designation', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('idx_staff_designations_scope'), 'staff_designations', ['scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('idx_staff_designations_designation'), 'staff_designations', ['designation'], unique=False)
    op.create_index(op.f('idx_staff_designations_active'), 'staff_designations', ['user_id', 'is_active'], unique=False, postgresql_where='(is_active IS TRUE)')
    # ### end Alembic commands ###
