"""remove_audit_columns_from_profiles

Revision ID: 34d3f200a213
Revises: d220fc24564e
Create Date: 2026-08-28 20:17:04.747372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34d3f200a213'
down_revision: Union[str, Sequence[str], None] = 'd220fc24564e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_admin_profiles_user_id_active'), table_name='admin_profiles', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('admin_profiles_updated_by_fkey'), 'admin_profiles', type_='foreignkey')
    op.drop_constraint(op.f('admin_profiles_created_by_fkey'), 'admin_profiles', type_='foreignkey')
    op.drop_constraint(op.f('admin_profiles_deleted_by_fkey'), 'admin_profiles', type_='foreignkey')
    op.drop_column('admin_profiles', 'updated_by')
    op.drop_column('admin_profiles', 'deleted_at')
    op.drop_column('admin_profiles', 'updated_at')
    op.drop_column('admin_profiles', 'deleted_by')
    op.drop_column('admin_profiles', 'created_by')
    op.drop_column('admin_profiles', 'created_at')
    op.drop_index(op.f('uq_student_profiles_user_id_active'), table_name='student_profiles', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('student_profiles_deleted_by_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_constraint(op.f('student_profiles_updated_by_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_constraint(op.f('student_profiles_created_by_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'updated_by')
    op.drop_column('student_profiles', 'deleted_at')
    op.drop_column('student_profiles', 'updated_at')
    op.drop_column('student_profiles', 'deleted_by')
    op.drop_column('student_profiles', 'created_by')
    op.drop_column('student_profiles', 'created_at')
    op.drop_index(op.f('uq_teacher_profiles_user_id_active'), table_name='teacher_profiles', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('teacher_profiles_updated_by_fkey'), 'teacher_profiles', type_='foreignkey')
    op.drop_constraint(op.f('teacher_profiles_created_by_fkey'), 'teacher_profiles', type_='foreignkey')
    op.drop_constraint(op.f('teacher_profiles_deleted_by_fkey'), 'teacher_profiles', type_='foreignkey')
    op.drop_column('teacher_profiles', 'updated_by')
    op.drop_column('teacher_profiles', 'deleted_at')
    op.drop_column('teacher_profiles', 'updated_at')
    op.drop_column('teacher_profiles', 'deleted_by')
    op.drop_column('teacher_profiles', 'created_by')
    op.drop_column('teacher_profiles', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_profiles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('teacher_profiles', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('teacher_profiles', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teacher_profiles_deleted_by_fkey'), 'teacher_profiles', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('teacher_profiles_created_by_fkey'), 'teacher_profiles', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('teacher_profiles_updated_by_fkey'), 'teacher_profiles', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('uq_teacher_profiles_user_id_active'), 'teacher_profiles', ['user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.add_column('student_profiles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('student_profiles', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('student_profiles', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_profiles_created_by_fkey'), 'student_profiles', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('student_profiles_updated_by_fkey'), 'student_profiles', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('student_profiles_deleted_by_fkey'), 'student_profiles', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('uq_student_profiles_user_id_active'), 'student_profiles', ['user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.add_column('admin_profiles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('admin_profiles', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('admin_profiles', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('admin_profiles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('admin_profiles', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('admin_profiles', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('admin_profiles_deleted_by_fkey'), 'admin_profiles', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('admin_profiles_created_by_fkey'), 'admin_profiles', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('admin_profiles_updated_by_fkey'), 'admin_profiles', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('uq_admin_profiles_user_id_active'), 'admin_profiles', ['user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
