"""create_principal_profiles

Revision ID: 5880bd561fff
Revises: 70e238654378
Create Date: 2026-09-11 15:48:33.764202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5880bd561fff'
down_revision: Union[str, Sequence[str], None] = '70e238654378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principal_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('school_setup_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_principal_profiles_school_id', 'principal_profiles', ['school_id'], unique=False)
    op.create_index('idx_principal_profiles_setup_completed', 'principal_profiles', ['school_setup_completed'], unique=False)

    # Migrate existing principal records to principal_profiles table
    op.execute(
        """
        INSERT INTO principal_profiles (id, user_id, school_id, pin_hash, school_setup_completed)
        SELECT gen_random_uuid(), id, school_id, pin_hash, COALESCE(school_setup_completed, false)
        FROM users
        WHERE role = 1
        """
    )

    op.drop_index(op.f('idx_users_school_id'), table_name='users')
    op.drop_constraint(op.f('users_school_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'school_setup_completed')
    op.drop_column('users', 'pin_hash')
    op.drop_column('users', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pin_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('school_setup_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_school_id_fkey'), 'users', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_users_school_id'), 'users', ['school_id'], unique=False)
    op.drop_index('idx_principal_profiles_setup_completed', table_name='principal_profiles')
    op.drop_index('idx_principal_profiles_school_id', table_name='principal_profiles')
    op.drop_table('principal_profiles')
    # ### end Alembic commands ###
