"""add_smtp_configurations_table

Revision ID: 60e1a71d60a2
Revises: a01c770df5c2
Create Date: 2026-09-01 14:44:35.903704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e1a71d60a2'
down_revision: Union[str, Sequence[str], None] = 'a01c770df5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('super_admin_id', sa.UUID(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=False),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('security', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['super_admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('super_admin_id', name='uq_smtp_super_admin_id')
    )
    op.create_index(op.f('ix_smtp_configurations_super_admin_id'), 'smtp_configurations', ['super_admin_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smtp_configurations_super_admin_id'), table_name='smtp_configurations')
    op.drop_table('smtp_configurations')
    # ### end Alembic commands ###
