"""create_staff_profiles_and_drop_admin_teacher

Revision ID: 633636be7219
Revises: a9ec1f5bb944
Create Date: 2026-08-29 19:49:18.249928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633636be7219'
down_revision: Union[str, Sequence[str], None] = 'a9ec1f5bb944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roll_no', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('father_first_name', sa.String(length=100), nullable=False),
    sa.Column('father_last_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_staff_profiles_roll_no', 'staff_profiles', ['roll_no'], unique=False)
    op.drop_index(op.f('idx_teacher_profiles_roll_no'), table_name='teacher_profiles', if_exists=True)
    op.drop_table('teacher_profiles', if_exists=True)
    op.drop_index(op.f('idx_admin_profiles_roll_no'), table_name='admin_profiles', if_exists=True)
    op.drop_table('admin_profiles', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('roll_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('father_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('father_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('admin_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('admin_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_admin_profiles_roll_no'), 'admin_profiles', ['roll_no'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('roll_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('father_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('father_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('teacher_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('teacher_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_teacher_profiles_roll_no'), 'teacher_profiles', ['roll_no'], unique=False)
    op.drop_index('idx_staff_profiles_roll_no', table_name='staff_profiles')
    op.drop_table('staff_profiles')
    # ### end Alembic commands ###
