"""update

Revision ID: 69822169ca18
Revises: a1b2c3d4e5f6
Create Date: 2026-10-02 11:58:17.839524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69822169ca18'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('setup_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('emblem_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schools_active', 'schools', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_schools_setup_completed', 'schools', ['setup_completed'], unique=False)
    op.create_index('uq_schools_code_active', 'schools', [sa.literal_column('lower(code)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key(None, 'class_subjects', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_conversation_participants'), 'conversation_participants', type_='unique')
    op.create_index('uq_conversation_participants', 'conversation_participants', ['conversation_id', 'user_id'], unique=True)
    op.create_foreign_key(None, 'conversations', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'houses', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'principal_profiles', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'school_classes', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sections', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff_profiles', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_profiles', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subjects', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wing_classes', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wings', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wings', type_='foreignkey')
    op.drop_constraint(None, 'wing_classes', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint(None, 'principal_profiles', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index('uq_conversation_participants', table_name='conversation_participants')
    op.create_unique_constraint(op.f('uq_conversation_participants'), 'conversation_participants', ['conversation_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_index('uq_schools_code_active', table_name='schools', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_schools_setup_completed', table_name='schools')
    op.drop_index('idx_schools_active', table_name='schools', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('schools')
    # ### end Alembic commands ###
