"""add_subjects_wings_and_house_emblem

Revision ID: 87db4281c667
Revises: f3a8b1c9e2d4
Create Date: 2026-09-06 14:46:15.290131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87db4281c667'
down_revision: Union[str, Sequence[str], None] = 'f3a8b1c9e2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subjects_school_id', 'subjects', ['school_id'], unique=False)
    op.create_index('uq_subjects_school_name', 'subjects', ['school_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('wings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wings_school_id', 'wings', ['school_id'], unique=False)
    op.create_index('uq_wings_school_name', 'wings', ['school_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('class_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_class_subjects_school_id', 'class_subjects', ['school_id'], unique=False)
    op.create_index('uq_class_subjects_class_subject', 'class_subjects', ['class_id', 'subject_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('wing_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('wing_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wing_classes_school_id', 'wing_classes', ['school_id'], unique=False)
    op.create_index('uq_wing_classes_wing_class', 'wing_classes', ['wing_id', 'class_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('houses', sa.Column('emblem_url', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'principal_onboarding_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_classes', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'school_classes', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'school_classes', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'schools', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'schools', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'schools', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sections', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sections', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sections', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_smtp_configurations_super_admin_id'), table_name='smtp_configurations')
    op.drop_constraint(op.f('uq_smtp_super_admin_id'), 'smtp_configurations', type_='unique')
    op.create_index(op.f('ix_smtp_configurations_admin_id'), 'smtp_configurations', ['admin_id'], unique=True)
    op.create_unique_constraint('uq_smtp_admin_id', 'smtp_configurations', ['admin_id'])
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint('uq_smtp_admin_id', 'smtp_configurations', type_='unique')
    op.drop_index(op.f('ix_smtp_configurations_admin_id'), table_name='smtp_configurations')
    op.create_unique_constraint(op.f('uq_smtp_super_admin_id'), 'smtp_configurations', ['admin_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_smtp_configurations_super_admin_id'), 'smtp_configurations', ['admin_id'], unique=True)
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint(None, 'principal_onboarding_tokens', type_='foreignkey')
    op.drop_column('houses', 'emblem_url')
    op.drop_index('uq_wing_classes_wing_class', table_name='wing_classes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_wing_classes_school_id', table_name='wing_classes')
    op.drop_table('wing_classes')
    op.drop_index('uq_class_subjects_class_subject', table_name='class_subjects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_class_subjects_school_id', table_name='class_subjects')
    op.drop_table('class_subjects')
    op.drop_index('uq_wings_school_name', table_name='wings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_wings_school_id', table_name='wings')
    op.drop_table('wings')
    op.drop_index('uq_subjects_school_name', table_name='subjects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_subjects_school_id', table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
