"""strictly_keep_only_requested_columns

Revision ID: 8b5d7c210781
Revises: 259771de0f8a
Create Date: 2026-08-29 18:54:34.132857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b5d7c210781'
down_revision: Union[str, Sequence[str], None] = '259771de0f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_admin_profiles_department'), table_name='admin_profiles')
    op.drop_column('admin_profiles', 'designation')
    op.drop_column('admin_profiles', 'employee_code')
    op.drop_column('admin_profiles', 'permissions_override')
    op.drop_column('admin_profiles', 'department')
    op.drop_column('student_profiles', 'guardian_name')
    op.drop_column('student_profiles', 'emergency_contact_name')
    op.drop_column('student_profiles', 'guardian_phone')
    op.drop_column('student_profiles', 'emergency_contact_phone')
    op.drop_column('student_profiles', 'address')
    op.drop_column('student_profiles', 'blood_group')
    op.drop_column('student_profiles', 'guardian_relation')
    op.drop_column('student_profiles', 'admission_number')
    op.drop_column('student_profiles', 'admission_date')
    op.drop_column('student_profiles', 'guardian_email')
    op.drop_column('student_profiles', 'medical_notes')
    op.drop_index(op.f('idx_teacher_profiles_department'), table_name='teacher_profiles')
    op.drop_index(op.f('idx_teacher_profiles_designation'), table_name='teacher_profiles')
    op.drop_column('teacher_profiles', 'employee_code')
    op.drop_column('teacher_profiles', 'bio')
    op.drop_column('teacher_profiles', 'specialization')
    op.drop_column('teacher_profiles', 'designation')
    op.drop_column('teacher_profiles', 'qualification')
    op.drop_column('teacher_profiles', 'department')
    op.drop_column('teacher_profiles', 'experience_years')
    op.drop_column('teacher_profiles', 'joining_date')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('teacher_profiles', sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('experience_years', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('qualification', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('specialization', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('teacher_profiles', sa.Column('employee_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_teacher_profiles_designation'), 'teacher_profiles', ['designation'], unique=False)
    op.create_index(op.f('idx_teacher_profiles_department'), 'teacher_profiles', ['department'], unique=False)
    op.add_column('student_profiles', sa.Column('medical_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('admission_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('admission_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_relation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('blood_group', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('emergency_contact_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('student_profiles', sa.Column('guardian_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('admin_profiles', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admin_profiles', sa.Column('permissions_override', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('admin_profiles', sa.Column('employee_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('admin_profiles', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_admin_profiles_department'), 'admin_profiles', ['department'], unique=False)
    # ### end Alembic commands ###
