"""remove_school_id_from_users

Revision ID: 9441b5ea8042
Revises: 633636be7219
Create Date: 2026-08-29 20:38:05.363778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9441b5ea8042'
down_revision: Union[str, Sequence[str], None] = '633636be7219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_users_school_id'), table_name='users')
    op.drop_index(op.f('idx_users_school_role'), table_name='users')
    op.drop_constraint(op.f('users_school_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'school_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_school_id_fkey'), 'users', 'schools', ['school_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('idx_users_school_role'), 'users', ['school_id', 'role'], unique=False)
    op.create_index(op.f('idx_users_school_id'), 'users', ['school_id'], unique=False)
    # ### end Alembic commands ###
