"""add_roles_classes_sections_houses_and_onboarding

Revision ID: a01c770df5c2
Revises: 33b9d6b393e2
Create Date: 2026-09-01 13:52:11.259919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01c770df5c2'
down_revision: Union[str, Sequence[str], None] = '33b9d6b393e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_houses_school_name', 'houses', ['school_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('principal_onboarding_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_onboarding_token_hash', 'principal_onboarding_tokens', ['token_hash'], unique=False)
    op.create_index('idx_onboarding_user_id', 'principal_onboarding_tokens', ['user_id'], unique=False)
    op.create_table('school_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_school_classes_school_order', 'school_classes', ['school_id', 'order_index'], unique=False)
    op.create_index('uq_school_classes_school_name', 'school_classes', ['school_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sections_school_id', 'sections', ['school_id'], unique=False)
    op.create_index('uq_sections_class_name', 'sections', ['class_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('schools', sa.Column('setup_completed', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('idx_schools_setup_completed', 'schools', ['setup_completed'], unique=False)
    op.add_column('users', sa.Column('school_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('pin_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('school_setup_completed', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index('idx_users_school_id', 'users', ['school_id'], unique=False)
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index('idx_users_school_id', table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'school_setup_completed')
    op.drop_column('users', 'pin_hash')
    op.drop_column('users', 'school_id')
    op.drop_index('idx_schools_setup_completed', table_name='schools')
    op.drop_column('schools', 'setup_completed')
    op.drop_index('uq_sections_class_name', table_name='sections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_sections_school_id', table_name='sections')
    op.drop_table('sections')
    op.drop_index('uq_school_classes_school_name', table_name='school_classes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_school_classes_school_order', table_name='school_classes')
    op.drop_table('school_classes')
    op.drop_index('idx_onboarding_user_id', table_name='principal_onboarding_tokens')
    op.drop_index('idx_onboarding_token_hash', table_name='principal_onboarding_tokens')
    op.drop_table('principal_onboarding_tokens')
    op.drop_index('uq_houses_school_name', table_name='houses', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('houses')
    # ### end Alembic commands ###
