"""super admin setup and school setup

Revision ID: a7bd5ef5ffbc
Revises: ea6606c2b12e
Create Date: 2026-09-01 16:46:32.176850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7bd5ef5ffbc'
down_revision: Union[str, Sequence[str], None] = 'ea6606c2b12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('login_mobile', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('school_setup_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_school_id', 'users', ['school_id'], unique=False)
    op.create_index('uq_users_email_active', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.create_index('uq_users_login_mobile_active', 'users', ['login_mobile'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key(None, 'houses', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'houses', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'houses', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'principal_onboarding_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_classes', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'school_classes', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'school_classes', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'schools', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'schools', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'schools', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sections', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sections', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'sections', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['deleted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['updated_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'smtp_configurations', 'users', ['super_admin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'staff_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint(None, 'smtp_configurations', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'schools', type_='foreignkey')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint(None, 'principal_onboarding_tokens', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_index('uq_users_login_mobile_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_users_email_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND email IS NOT NULL'))
    op.drop_index('idx_users_school_id', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
