"""update admin, teacher, student tables

Revision ID: a9ec1f5bb944
Revises: 8b5d7c210781
Create Date: 2026-08-29 19:11:35.679181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ec1f5bb944'
down_revision: Union[str, Sequence[str], None] = '8b5d7c210781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
