"""add_staff_lifecycle_and_tokens

Revision ID: b14daa4b88fd
Revises: 1f178b3f13c2
Create Date: 2026-09-20 15:05:54.788534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14daa4b88fd'
down_revision: Union[str, Sequence[str], None] = '1f178b3f13c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_onboarding_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staff_onboarding_token_hash', 'staff_onboarding_tokens', ['token_hash'], unique=False)
    op.create_index('idx_staff_onboarding_user_id', 'staff_onboarding_tokens', ['user_id'], unique=False)
    op.add_column('staff_profiles', sa.Column('school_id', sa.UUID(), nullable=True))
    op.add_column('staff_profiles', sa.Column('pin_hash', sa.Text(), nullable=True))
    op.add_column('staff_profiles', sa.Column('status', sa.String(length=30), server_default='PENDING_ACTIVATION', nullable=False))
    op.add_column('staff_profiles', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('staff_profiles', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('staff_profiles', sa.Column('designation', sa.String(length=100), nullable=True))
    op.create_index('idx_staff_profiles_school_id', 'staff_profiles', ['school_id'], unique=False)
    op.create_index('idx_staff_profiles_status', 'staff_profiles', ['status'], unique=False)
    op.create_foreign_key(None, 'staff_profiles', 'schools', ['school_id'], ['id'], ondelete='CASCADE')

    # Mark existing staff with password as ACTIVE
    op.execute(
        """
        UPDATE staff_profiles
        SET status = 'ACTIVE', activated_at = NOW()
        WHERE user_id IN (
            SELECT id FROM users WHERE password_hash IS NOT NULL
        )
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_profiles', type_='foreignkey')
    op.drop_index('idx_staff_profiles_status', table_name='staff_profiles')
    op.drop_index('idx_staff_profiles_school_id', table_name='staff_profiles')
    op.drop_column('staff_profiles', 'designation')
    op.drop_column('staff_profiles', 'department')
    op.drop_column('staff_profiles', 'activated_at')
    op.drop_column('staff_profiles', 'status')
    op.drop_column('staff_profiles', 'pin_hash')
    op.drop_column('staff_profiles', 'school_id')
    op.drop_index('idx_staff_onboarding_user_id', table_name='staff_onboarding_tokens')
    op.drop_index('idx_staff_onboarding_token_hash', table_name='staff_onboarding_tokens')
    op.drop_table('staff_onboarding_tokens')
    # ### end Alembic commands ###
