"""add admin, teacher, student tables

Revision ID: b6e09975e211
Revises: 34d3f200a213
Create Date: 2026-08-28 20:18:25.493774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e09975e211'
down_revision: Union[str, Sequence[str], None] = '34d3f200a213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_admin_profiles_employee_code', 'admin_profiles', ['employee_code'], unique=False)
    op.create_index('idx_student_profiles_admission_number', 'student_profiles', ['admission_number'], unique=False)
    op.create_index('idx_teacher_profiles_employee_code', 'teacher_profiles', ['employee_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teacher_profiles_employee_code', table_name='teacher_profiles')
    op.drop_index('idx_student_profiles_admission_number', table_name='student_profiles')
    op.drop_index('idx_admin_profiles_employee_code', table_name='admin_profiles')
    # ### end Alembic commands ###
