"""add admin, teacher, student tables

Revision ID: d220fc24564e
Revises: 1ba7d9e67683
Create Date: 2026-08-28 20:01:24.302456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd220fc24564e'
down_revision: Union[str, Sequence[str], None] = '1ba7d9e67683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'nationality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('nationality', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
