from datetime import datetime
from pydantic import BaseModel, ConfigDict, EmailStr, Field


class PrincipalEmailConfigRequest(BaseModel):
    """
    User-friendly Email Setup payload for Principal accounts.
    Allows Principal to configure email without knowing technical SMTP host/port details.
    """
    email: EmailStr = Field(..., description="School or Principal outgoing email address")
    app_password: str = Field(..., min_length=1, description="16-character App Password generated by email provider")
    sender_name: str | None = Field(default=None, max_length=255, description="Friendly sender name e.g. School Name")
    smtp_host: str | None = Field(default=None, description="Optional custom host (auto-derived if omitted)")
    smtp_port: int | None = Field(default=None, description="Optional custom port (defaults to 587)")
    security: str | None = Field(default="TLS", description="Security protocol mode")


class PrincipalEmailConfigResponse(BaseModel):
    """
    Representation of Principal Email Setup.
    """
    is_configured: bool = Field(..., description="Whether outgoing email is configured and active")
    email: str | None = Field(default=None, description="Configured sender email address")
    sender_name: str | None = Field(default=None, description="Configured display sender name")
    is_password_set: bool = Field(default=False, description="Whether an app password has been saved")
    app_password: str | None = Field(default=None, description="Saved app password")
    updated_at: datetime | None = Field(default=None, description="Last update timestamp")

    model_config = ConfigDict(from_attributes=True)


class PrincipalEmailTestRequest(BaseModel):
    """Payload to test email setup connection."""
    email: EmailStr = Field(..., description="Email address to authenticate with")
    app_password: str = Field(..., min_length=1, description="App password to test")
    smtp_host: str | None = Field(default=None, description="Optional host")
    smtp_port: int | None = Field(default=587, description="Port")
    security: str | None = Field(default="TLS", description="Security mode")


class PrincipalEmailTestResponse(BaseModel):
    """Response of email setup test connection."""
    success: bool
    message: str
